version: '3.7'
services:

  backend:
    container_name: backend
    restart: always
    build:
      context: server
      target: development
    volumes:
      - ./server:/usr/src/reading-tasks-manager-backend
      - /usr/src/reading-tasks-manager-backend/node_modules #docker-compose up --build -V to rebuid if install any packages
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      #- 3000:3000
    command: yarn start:dev
    #command: bash -c 'while !</dev/tcp/mongo/27017; do sleep 1; done; yarn start:dev'
    env_file: 
      - .env
    networks:
      nest-mongo-network:
          aliases:
            - nest
  
  frontend:
    container_name: frontend
    restart: always
    build:
      context: client
      target: development
    volumes:
      - ./client:/usr/src/reading-tasks-manager-frontend
      - /usr/src/reading-tasks-manager-frontend/node_modules #docker-compose up --build -V to rebuid if install any packages
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
      #- 4200:4200
    command: yarn start
    env_file: 
      - .env
    networks:
      nest-mongo-network:
          aliases:
            - react
    depends_on:
      - backend

networks:
  nest-mongo-network:
    external: true