version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./server/mongodb/database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      nest-mongo-network:
          aliases:
            - mongo

  mongo-express:
    image: mongo-express
    container_name: mongodb-ui
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      nest-mongo-network:
          aliases:
            - mongo-ui
    depends_on:
      - mongo

  backend:
    container_name: backend
    restart: always
    build:
      context: server
      target: development
    volumes:
      - ./server:/usr/src/reading-task-manger-backend
      - /usr/src/reading-task-manger-backend/node_modules #docker-compose up --build -V to rebuid if install any packages
    ports:
      - 3000:3000
    command: yarn start:dev
    #command: bash -c 'while !</dev/tcp/mongo/27017; do sleep 1; done; yarn start:dev' #wait for elasticsearch to fully loaded 
    #env_file:
    #  - .env
    networks:
      nest-mongo-network:
          aliases:
            - nest
    depends_on:
      - mongo

networks:
  nest-mongo-network:
    external: true